name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Build Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config

      - name: Prepare Autotools
        run: |
          # هذه الخطوات تحل مشكلة الماكرو المفقود LT_SYS_SYMBOL_USCORE
          autoupdate || true
          libtoolize || true
          
      - name: Build with Buildozer
        uses: ArtemGr/buildozer-action@v1
        with:
          command: android debug
          buildozer_version: master
